name: Spendify BE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: backend

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    # - run: npm ci
    - run: npm run build --if-present
    - run: npm test